# Generated by Django 2.1.1 on 2018-12-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModel',
            new_name='Todo',
        ),
    ]
